
import RentalYieldCalculator from '@/components/RentalYieldCalculator';

const Index = () => {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <div className="flex-1">
        <RentalYieldCalculator />
      </div>
      <footer className="border-t border-border bg-background py-4 px-6">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row justify-between items-center gap-2">
          <p className="text-sm text-muted-foreground">
            Copyright © 
            <a href="https://roi.realtytools.pl/">
              ROI.RealtyTools.pl
            </a>
            : Rental Yield Calculator - Real Estate Investment ROI Analysis Tool. All rights reserved.
          </p>
          <p className="text-xs text-muted-foreground opacity-70">
            tool generated by AI
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Index;
